version: '3'

services:
  frontend:
    build: 
      context: .
      dockerfile: simple_UI/Dockerfile
    image: leodocker2021/my-repo-mlops-frontend:latest
    environment:
      #HOST: 192.168.64.2
      HOST: db
      #HOST: ${HOST:-$(hostname -I | awk '{print $1}')}
    ports:
      - 8501:8501
    depends_on:
      - api-train
      - api-inference
      - api-store-info
      - adminer
    volumes:
        - my-data:/work2

  api-train:
    build:
      context: .
      dockerfile: simple_train/Dockerfile
    image: leodocker2021/my-repo-mlops-api-train:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    volumes:
      - my-data:/work2
      - my-data-inference:/inference
    ports:
      - "8502:82"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  api-inference:
    build:
      context: .
      dockerfile: simple_inference/Dockerfile
    image: leodocker2021/my-repo-mlops-api-inference:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8503:83"
    depends_on:
      - db
    volumes:
      - my-data:/work2
      - my-data-inference:/inference

  api-store-info:
    build:
      context: .
      dockerfile: simple_store_info/Dockerfile
    image: leodocker2021/my-repo-mlops-api-store-info:latest
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    ports:
      - "8504:84"
    depends_on:
      - db
    volumes:
      - my-data:/work2
      - my-data-inference:/inference

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_DRIVER: postgres
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    depends_on:
      - db

  mlflow:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    image: leodocker2021/my-repo-mlops-mlflow:latest
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      - db
      - minio
    environment:
      #- MLFLOW_DEFAULT_ARTIFACT_ROOT=s3://mlop-s3/artifacts
      #- MLFLOW_S3_ENDPOINT_URL=http://localhost:9000
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=supersecret

  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=supersecret
      #- MINIO_DEFAULT_BUCKET=mlop-s3/artifacts
      #- MINIO_ACCESS_KEY=minioaccesskey
      #- MINIO_SECRET_KEY=miniosecretkey
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio:/data
    restart: unless-stopped

volumes:
  my-data:
  my-data-inference:
