version: '4'

services:
  frontend:
    build: 
      context: .
      dockerfile: simple_UI/Dockerfile
    ports:
      - 8501:8501
    depends_on:
      - api_train
      - api_inference
    volumes:
        - my-data:/work0
  api_train:
    build:
      context: .
      dockerfile: simple_train/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    volumes:
      - my-data:/work1
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  api_inference:
    build:
      context: .
      dockerfile: simple_inference/Dockerfile
    ports:
      - "8001:81"
    depends_on:
      - db
    volumes:
      - my-data:/work2
volumes:
  my-data:
